name: pipeline ci/cd - publish mapping package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: setup gitversion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: semantic versioning
        uses: gittools/actions/gitversion/execute@v0
        id: gitversion

      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: restore dependencies
        run: dotnet restore

      - name: build
        run: dotnet build --configuration Release --no-restore

      - name: set version and pack
        id: pack
        run: |
          VERSION="${{ steps.gitversion.outputs.semVer }}"
          echo "use version: $VERSION"
          dotnet pack -c Release -p:PackageVersion=$VERSION -o ./output --no-build
          echo "package_version=$VERSION" >> $GITHUB_OUTPUT

      - name: nuget login (oidc → temp api key)
        uses: NuGet/login@v1
        id: login

      - name: push package to nuget
        run: dotnet nuget push ./output/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate